###
GET http://localhost:3000

###
GET http://localhost:3000/posts

###
GET http://localhost:3000/posts?owner=tal2

###

GET http://localhost:3000/posts/67c7290d7be99e4129c66e33

###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "owner": "tal2",
    "title": "My first post",
    "content": "This is my first post"
   
}

###
DELETE http://localhost:3000/posts/67c7290d7be99e4129c66e33
 